export let FETCH_TAFSER_REQUEST = "FETCH_TAFSER_REQUEST";
export let FETCH_TAFSER_SUCCESS = "FETCH_TAFSER_SUCCESS";
export let FETCH_TAFSER_FAILURE = "FETCH_TAFSER_FAILURE";
export let SET_SURAH_ID = "SET_SURAH_ID";
export let SET_AYAH_ID = "SET_AYAH_ID";
