export let FETCH_TAFSER_AYAH_REQUEST = "FETCH_TAFSER_AYAH_REQUEST";
export let FETCH_TAFSER_AYAH_SUCCESS = "FETCH_TAFSER_AYAH_SUCCESS";
export let FETCH_TAFSER_AYAH_FAILURE = "FETCH_TAFSER_AYAH_FAILURE";
export let SET_SURAH_ID = "SET_SURAH_ID";
export let SET_AYAH_ID = "SET_AYAH_ID";