export let FETCH_RECITER_NAMES_REQUEST =
  "FETCH_RECITER_NAMES_REQUEST";
export let FETCH_RECITER_NAMES_SUCCESS =
  "FETCH_RECITER_NAMES_SUCCESS";
export let FETCH_RECITER_NAMES_FAILURE =
  "FETCH_RECITER_NAMES_FAILURE";
