export let FETCH_SURAH_TITLE_REQUEST = "FETCH_SURAH_TITLE_REQUEST";
export let FETCH_SURAH_TITLE_SUCCESS = "FETCH_SURAH_TITLE_SUCCESS";
export let FETCH_SURAH_TITLE_FAILURE = "FETCH_SURAH_TITLE_FAILURE";
