export let FETCH_AUDIO_REQUEST = "FETCH_AUDIO_REQUEST";
export let FETCH_AUDIO_SUCCESS = "FETCH_AUDIO_SUCCESS";
export let FETCH_AUDIO_FAILURE = "FETCH_AUDIO_FAILURE";
export let DELETE_DATA = "DELETE_DATA";
export let CHANGE_RECITER_ID = "CHANGE_RECITER_ID";
