export let CHANGE_MENU_MODE = "CHANGE_MENU_MODE";
export let CHANGE_MICROPHONE_MODE = "CHANGE_MICROPHONE_MODE";
export let CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export let CHANGE_SETTING_MENU = "CHANGE_SETTING_MENU";
export let CHANGE_SETTING_PAGE = "CHANGE_SETTING_PAGE";
export let OPEN_CLOSE_TAFSER = "OPEN_CLOSE_TAFSER";
// export let OPEN_CLOSE_TRANSLATION_SETTING = "OPEN_CLOSE_TRANSLATION_SETTING";
