export let FETCH_SURAH_SEARCH_REQUEST = "FETCH_SURAH_SEARCH_REQUEST";
export let FETCH_SURAH_SEARCH_SUCCESS = "FETCH_SURAH_SEARCH_SUCCESS";
export let FETCH_SURAH_SEARCH_FAILURE = "FETCH_SURAH_SEARCH_FAILURE";
export let SET_TEXT_OF_SEARCH = "SET_TEXT_OF_SEARCH";
export let CHANGE_SEARCH_MENU_OPEN = "CHANGE_SEARCH_MENU_OPEN";
export let CHANGE_SEARCH_PAGE = "CHANGE_SEARCH_PAGE";
