export let FETCH_SEARCH_DATA_REQUEST = "FETCH_SEARCH_DATA_REQUEST";
export let FETCH_SEARCH_DATA_SUCCESS = "FETCH_SEARCH_DATA_SUCCESS";
export let FETCH_SEARCH_DATA_FAILURE = "FETCH_SEARCH_DATA_FAILURE";
